version: '3.8'
services:
  chatllm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspaces:chached
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: -1
              capabilities: [gpu]
